# -*- coding: utf-8 -*-
"""phonenumber_identifier.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LYr7LLjBZFvqZvJWR9_uQMMjf5Qkufg0
"""

pip install phonenumbers

import phonenumbers

from phonenumbers import geocoder
from phonenumbers import carrier

Phone1=input("Enter Phone Number:-")
phone2=phonenumbers.parse(Phone1)
service=phonenumbers.parse(Phone1)

print("Country Name:",geocoder.description_for_number(phone2,"en"))

print("Provider :",carrier.name_for_number(service,'en'))